name: chorder
description: "A chord-focused piano companion app for music transcription and practice."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
    