name: diatonic
description: "A chord-focused piano companion app for music transcription and practice."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  window_size: ^0.1.0
  file_picker: ^10.1.2
  wav: ^1.4.0
  just_audio: ^0.10.4
  just_audio_windows: ^0.2.2
  path: ^1.9.1
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
    
msix_config:
  display_name: Diatonic
  identity_name: org.diatonic.diatonic
  publisher_display_name: Eric Kort
  # Must match your cert Subject (adjust to your cert):
  publisher: "CN=Eric Kort, O=Your Org, C=US"
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities:
    - internetClient